[project]
name = "entity-linker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.142.2",
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.4",
    "spacy>=3.8.16",
    "uvicorn>=0.54.0",
]

[dependency-groups]
dev = [
    "mypy>=2.4.0",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
